spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: a123
    url: jdbc:mysql://localhost:3306/testschema?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: suzi
  mail:
    host: smtp.gmail.com
    username: itwillproject1@gmail.com
    password: fflfodpaiexxbnje
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace
    root: info

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  #devtools
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false

