spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/testschema?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: suzi
    password: a123
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    username: itwillproject1@gmail.com
    password: fflfodpaiexxbnje
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  #devtools
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace
    root: info
